name: gitleaks

on:
  pull_request:
      branches: [ main, staging ]
  push:
    branches: [ main, master ]
  workflow_dispatch:
permissions: 
  contents: read
  security-events: write
  actions: read
  issues: write
  pull-requests: write
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      - name: Upload GitLeaks report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: results.sarif
          retention-days: 5
          if-no-files-found: warn
