name: gitleaks

on:
  pull_request:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # run once a day at 4 AM UTC

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
